### PR TITLE
feat: Add error field to events/links on spans that are error spans

### PR DESCRIPTION
**Pull request by cartermp**
This fixes https://github.com/honeycombio/husky/issues/155

Assuming we agree there's nothing wrong with doing this

### CODE REVIEW

**Review by kentquirk — APPROVED** [review]
Talked about it in sync; looks good.

**Comment by vreynolds** [comment]
@cartermp looking at your comment in the issue:
> we'd just want to make sure it doesn't mess up the UI somehow.

Did you get a chance to check this out in the UI?

**Comment by cartermp** [comment]
Nope, wouldn't know how other than updating hound.

**Comment by vreynolds** [comment]
checked it out locally, and don't see any obvious issues

**Pull request merged**
